# Generated by Django 3.2.16 on 2023-02-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger_chequebook',
            name='ledger_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
